# Generated by Django 3.1.4 on 2021-01-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ZN', 'Znalosti'), ('SC', 'Schopnosti'), ('PR', 'Přátelství')], default='ZN', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['datum']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_full_name_displayed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
                ('splněno', models.ManyToManyField(to='website.UserProfile')),
            ],
        ),
    ]
