# Generated by Django 3.1.4 on 2021-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210110_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='splněno',
            field=models.ManyToManyField(blank=True, null=True, to='website.UserProfile'),
        ),
    ]
