# Generated by Django 3.1.4 on 2021-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('ZN', 'Znalosti'), ('SC', 'Schopnosti'), ('PR', 'Přátelství')], default='ZN', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
