# Generated by Django 3.1.4 on 2021-01-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210110_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-datum']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='nazev',
        ),
    ]
