# Generated by Django 3.1.4 on 2021-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210111_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge_PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('splněno', models.ManyToManyField(blank=True, null=True, to='website.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('splněno', models.ManyToManyField(blank=True, null=True, to='website.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_ZN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('splněno', models.ManyToManyField(blank=True, null=True, to='website.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='kategorie',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='splněno',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
