# Generated by Django 3.1.4 on 2021-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210112_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge_sc',
            name='splněno',
        ),
        migrations.AddField(
            model_name='challenge_sc',
            name='splneno',
            field=models.ManyToManyField(blank=True, null=True, to='website.UserProfile'),
        ),
    ]
