# Generated by Django 3.1.4 on 2021-01-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210113_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge_pr',
            old_name='splněno',
            new_name='splneno',
        ),
        migrations.RenameField(
            model_name='challenge_zn',
            old_name='splněno',
            new_name='splneno',
        ),
    ]
