# Generated by Django 3.1.4 on 2021-01-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210114_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='barva',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='kategorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datum',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='splneno',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vyzva',
        ),
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='website.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Napište zprávu.'),
        ),
        migrations.CreateModel(
            name='Solving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('answer', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='website.challenge')),
                ('solved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_by', to='website.userprofile')),
            ],
        ),
    ]
