# Generated by Django 3.1.4 on 2021-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solving',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='Tady můžeš napsat něco o sobě...', null=True),
        ),
    ]
