# Generated by Django 3.1.4 on 2021-01-17 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210114_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solving',
            options={'ordering': ['is_solved']},
        ),
        migrations.AddField(
            model_name='solving',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(help_text='blue/red/green', max_length=60),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
