# Generated by Django 3.1.4 on 2021-01-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210117_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solving',
            options={'ordering': ['is_solved', '-date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post',
        ),
    ]
